### ISSUE TITLE
DLL load failed while importing custom_rasterizer_kernel

### ISSUE THREAD

**Issue by hooknick1979** [kijai/ComfyUI-Hunyuan3DWrapper#37]
I am getting closer to having this work. I can generate messes no problem. I did not see this exact issue listed. I had the earlier issue with having to re-install the custom_rasterizer. Now I am stuck here with the DLL load failed while importing it. 

Decoded mesh with 270692 vertices and 541376 faces
Removed floaters, resulting in 270682 vertices and 541360 faces
Removed degenerate faces, resulting in 270682 vertices and 541360 faces
Reduced faces, resulting in 25002 vertices and 50000 faces
camera_distance: 1.45
!!! Exception during processing !!! DLL load failed while importing custom_rasterizer_kernel: The specified procedure could not be found.
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable_312\ComfyUI\execution.py", line 327, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable_312\ComfyUI\execution.py", line 202, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable_312\ComfyUI\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\ComfyUI_windows_portable_312\ComfyUI\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable_312\ComfyUI\custom_nodes\ComfyUI-Hunyuan3DWrapper\nodes.py", line 405, in process
    self.render = MeshRender(
                  ^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable_312\ComfyUI\custom_nodes\ComfyUI-Hunyuan3DWrapper\hy3dgen\texgen\differentiable_renderer\mesh_render.py", line 158, in __init__
    import custom_rasterizer as cr
  File "D:\ComfyUI_windows_portable_312\python_embeded\Lib\site-packages\custom_rasterizer\__init__.py", line 32, in <module>
    from .render import *
  File "D:\ComfyUI_windows_portable_312\python_embeded\Lib\site-packages\custom_rasterizer\render.py", line 25, in <module>
    import custom_rasterizer_kernel
ImportError: DLL load failed while importing custom_rasterizer_kernel: The specified procedure could not be found.

Prompt executed in 50.83 seconds

**Comment by hooknick1979** [comment]
This was all done with a fresh install as well. Here is some system info. 

D:\ComfyUI_windows_portable_312>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2025-01-29 16:21:57.683
** Platform: Windows
** Python version: 3.12.8 (tags/v3.12.8:2dc476b, Dec  3 2024, 19:30:04) [MSC v.1942 64 bit (AMD64)]
** Python executable: D:\ComfyUI_windows_portable_312\python_embeded\python.exe
** ComfyUI Path: D:\ComfyUI_windows_portable_312\ComfyUI
** ComfyUI Base Folder Path: D:\ComfyUI_windows_portable_312\ComfyUI
** User directory: D:\ComfyUI_windows_portable_312\ComfyUI\user
** ComfyUI-Manager config path: D:\ComfyUI_windows_portable_312\ComfyUI\user\default\ComfyUI-Manager\config.ini
** Log path: D:\ComfyUI_windows_portable_312\ComfyUI\user\comfyui.log

Prestartup times for custom nodes:
   1.2 seconds: D:\ComfyUI_windows_portable_312\ComfyUI\custom_nodes\ComfyUI-Manager

Checkpoint files will always be loaded safely.
Total VRAM 24564 MB, total RAM 98084 MB
pytorch version: 2.6.0+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
Using pytorch attention
ComfyUI version: 0.3.12
[Prompt Server] web root: D:\ComfyUI_windows_portable_312\ComfyUI\web
### Loading: ComfyUI-Manager (V3.11)
### ComfyUI Revision: 3085 [6ff2e4d5] *DETACHED | Released on '2025-01-29'

**Comment by Ctrixago** [comment]
@hooknick1979 Hi! Did you run the python commands through "Comfy3D_WinPortable\python_embedded\python.exe"? If not, it's worth a try) (I'm talking about the commands from "Installation").

**Comment by drjstudios** [comment]
> [@hooknick1979](https://github.com/hooknick1979) Hi! Did you run the python commands through "Comfy3D_WinPortable\python_embedded\python.exe"? If not, it's worth a try) (I'm talking about the commands from "Installation").

hi! i was wondering for this, is it possible to do this without a portable version of comfyui? thanks!

**Comment by kijai** [comment]
I added pytorch 2.6.0 compatible wheel now, it should help with the latest comfy portable which does use pytorch 2.6.0.

**Comment by MicahJank** [comment]
If you are like me...i downloaded the latest version of comfyui which has torch 2.6.0 and cuda 126...i tried kijai's wheel file and i was still getting errors so i tried to follow the instructions from https://github.com/kijai/ComfyUI-Hunyuan3DWrapper/issues/14 to build the wheel myself...this worked however make sure to take note of the wheel version..in my case the one that was built was torch 2.5.0 with cuda 124...even installing this didnt work and i figured probably because comfyui was running with later version. So i manually removed the torch audio and vision etc folders..from the pyhton_embeded/lib/site-packages folder...any of the ones that was using 2.6.0 and then from the pytorch website i got the installation command for torch 2.5.0 with cuda124 (what matched the wheel that was built) https://pytorch.org/get-started/previous-versions/ and then from using the python_embeded/python.exe command i installed that version...now i can run the workflow with no issues. Hopefully this helps someone.

**Comment by hooknick1979** [comment]
> I added pytorch 2.6.0 compatible wheel now, it should help with the latest comfy portable which does use pytorch 2.6.0.

I had to work on some other things, but wanted to come back and say this worked lovely. Thank you!

**Comment by jiperezga** [comment]
I made the following modifications to the setup.py, rasterizer.cpp files and it worked for me to resolve the error "Hy3DRenderMultiView DLL load failed while importing custom_rasterizer_kernel"
1) Go to folder `ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Hunyuan3DWrapper\hy3dgen\texgen\custom_rasterizer`
2) Edit setup.py for:
## Begin setup.py 
``from setuptools import setup, find_packages``
``from torch.utils.cpp_extension import BuildExtension, CUDAExtension``
``import pybind11``

``# build custom rasterizer``
``# build with `python setup.py install``
``# nvcc is needed``

``custom_rasterizer_module = CUDAExtension(``
``    'custom_rasterizer_kernel',``
``    [``
``        'lib/custom_rasterizer_kernel/rasterizer.cpp',``
``        'lib/custom_rasterizer_kernel/grid_neighbor.cpp',``
``        'lib/custom_rasterizer_kernel/rasterizer_gpu.cu',``
``    ],``
``    include_dirs=[pybind11.get_include()]``
``)``

``setup(``
``    packages=find_packages(),``
``    version='0.1',``
``    name='custom_rasterizer',``
``    include_package_data=True,``
``    package_dir={'': '.'},``
``    ext_modules=[``
``        custom_rasterizer_module,``
``    ],``
``    cmdclass={``
``        'build_ext': BuildExtension``
``    }``
)
## End setup.py

3) Open a cmd terminal in the setup.py path and run `python setup.py install`
4) Go to folder `ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Hunyuan3DWrapper\hy3dgen\texgen\custom_rasterizer\lib\custom_rasterizer_kernel`
5) Edit rasterizer.cpp like:
## Begin rasterizer.cpp
`#include "rasterizer.h"`
`#include <pybind11/pybind11.h>`
`#include <pybind11/numpy.h>`
`#include <torch/extension.h>`

`namespace py = pybind11;`

`void rasterizeTriangleCPU(int idx, float* vt0, float* vt1, float* vt2, int width, int height, INT64* zbuffer, float* d, float occlusion_truncation) {`
`    float x_min = std::min(vt0[0], std::min(vt1[0], vt2[0]));`
`    float x_max = std::max(vt0[0], std::max(vt1[0], vt2[0]));`
`    float y_min = std::min(vt0[1], std::min(vt1[1], vt2[1]));`
`    float y_max = std::max(vt0[1], std::max(vt1[1], vt2[1]));`

`    for (int px = x_min; px < x_max + 1; ++px) {`
`        if (px < 0 || px >= width)`
`            continue;`
`        for (int py = y_min; py < y_max + 1; ++py) {`
`            if (py < 0 || py >= height)`
`                continue;`
`            float vt[2] = {px + 0.5, py + 0.5};`
`            float baryCentricCoordinate[3];`
`            calculateBarycentricCoordinate(vt0, vt1, vt2, vt, baryCentricCoordinate);`
`            if (isBarycentricCoordInBounds(baryCentricCoordinate)) {`
`                int pixel = py * width + px;`
`                if (zbuffer == 0) {`
`                    zbuffer[pixel] = (INT64)(idx + 1);`
`                    continue;`
`                }`

`                float depth = baryCentricCoordinate[0] * vt0[2] + baryCentricCoordinate[1] * vt1[2] + baryCentricCoordinate[2] * vt2[2];`
`                float depth_thres = 0;`
`                if (d) {`
`                    depth_thres = d[pixel] * 0.49999f + 0.5f + occlusion_truncation;`
`                }`

`                int z_quantize = depth * (2 << 17);`
`                INT64 token = (INT64)z_quantize * MAXINT + (INT64)(idx + 1);`
`                if (depth < depth_thres)`
`                    continue;`
`                zbuffer[pixel] = std::min(zbuffer[pixel], token);`
`            }`
`        }`
`    }`
`}`

`void barycentricFromImgcoordCPU(float* V, int* F, int* findices, INT64* zbuffer, int width, int height, int num_vertices, int num_faces,`
`    float* barycentric_map, int pix)`
`{`
`    INT64 f = zbuffer[pix] % MAXINT;`
`    if (f == (MAXINT - 1)) {`
`        findices[pix] = 0;`
`        barycentric_map[pix * 3] = 0;`
`        barycentric_map[pix * 3 + 1] = 0;`
`        barycentric_map[pix * 3 + 2] = 0;`
`        return;`
`    }`
`    findices[pix] = f;`
`    f -= 1;`
`    float barycentric[3] = {0, 0, 0};`
`    if (f >= 0) {`
`        float vt[2] = {float(pix % width) + 0.5f, float(pix / width) + 0.5f};`
`        float* vt0_ptr = V + (F[f * 3] * 4);`
`        float* vt1_ptr = V + (F[f * 3 + 1] * 4);`
`        float* vt2_ptr = V + (F[f * 3 + 2] * 4);`

`        float vt0[2] = {(vt0_ptr[0] / vt0_ptr[3] * 0.5f + 0.5f) * (width - 1) + 0.5f, (0.5f + 0.5f * vt0_ptr[1] / vt0_ptr[3]) * (height - 1) + 0.5f};`
`        float vt1[2] = {(vt1_ptr[0] / vt1_ptr[3] * 0.5f + 0.5f) * (width - 1) + 0.5f, (0.5f + 0.5f * vt1_ptr[1] / vt1_ptr[3]) * (height - 1) + 0.5f};`
`        float vt2[2] = {(vt2_ptr[0] / vt2_ptr[3] * 0.5f + 0.5f) * (width - 1) + 0.5f, (0.5f + 0.5f * vt2_ptr[1] / vt2_ptr[3]) * (height - 1) + 0.5f};`

`        calculateBarycentricCoordinate(vt0, vt1, vt2, vt, barycentric);`

`        barycentric[0] = barycentric[0] / vt0_ptr[3];`
`        barycentric[1] = barycentric[1] / vt1_ptr[3];`
`        barycentric[2] = barycentric[2] / vt2_ptr[3];`
`        float w = 1.0f / (barycentric[0] + barycentric[1] + barycentric[2]);`
`        barycentric[0] *= w;`
`        barycentric[1] *= w;`
`        barycentric[2] *= w;`

`    }`
`    barycentric_map[pix * 3] = barycentric[0];`
`    barycentric_map[pix * 3 + 1] = barycentric[1];`
`    barycentric_map[pix * 3 + 2] = barycentric[2];`
`}`

`void rasterizeImagecoordsKernelCPU(float* V, int* F, float* d, INT64* zbuffer, float occlusion_trunc, int width, int height, int num_vertices, int num_faces, int f)`
`{`
`    float* vt0_ptr = V + (F[f * 3] * 4);`
`    float* vt1_ptr = V + (F[f * 3 + 1] * 4);`
`    float* vt2_ptr = V + (F[f * 3 + 2] * 4);`

`    float vt0[3] = {(vt0_ptr[0] / vt0_ptr[3] * 0.5f + 0.5f) * (width - 1) + 0.5f, (0.5f + 0.5f * vt0_ptr[1] / vt0_ptr[3]) * (height - 1) + 0.5f, vt0_ptr[2] / vt0_ptr[3] * 0.49999f + 0.5f};`
`    float vt1[3] = {(vt1_ptr[0] / vt1_ptr[3] * 0.5f + 0.5f) * (width - 1) + 0.5f, (0.5f + 0.5f * vt1_ptr[1] / vt1_ptr[3]) * (height - 1) + 0.5f, vt1_ptr[2] / vt1_ptr[3] * 0.49999f + 0.5f};`
`    float vt2[3] = {(vt2_ptr[0] / vt2_ptr[3] * 0.5f + 0.5f) * (width - 1) + 0.5f, (0.5f + 0.5f * vt2_ptr[1] / vt2_ptr[3]) * (height - 1) + 0.5f, vt2_ptr[2] / vt2_ptr[3] * 0.49999f + 0.5f};`

`    rasterizeTriangleCPU(f, vt0, vt1, vt2, width, height, zbuffer, d, occlusion_trunc);`
`}`

`std::vector<torch::Tensor> rasterize_image_cpu(torch::Tensor V, torch::Tensor F, torch::Tensor D,`
`    int width, int height, float occlusion_truncation, int use_depth_prior)`
`{`
`    int num_faces = F.size(0);`
`    int num_vertices = V.size(0);`
`    auto options = torch::TensorOptions().dtype(torch::kInt32).requires_grad(false);`
`    auto INT64_options = torch::TensorOptions().dtype(torch::kInt64).requires_grad(false);`
`    auto findices = torch::zeros({height, width}, options);`
`    INT64 maxint = (INT64)MAXINT * (INT64)MAXINT + (MAXINT - 1);`
`    auto z_min = torch::ones({height, width}, INT64_options) * (int64_t)maxint;`

`    if (!use_depth_prior) {`
`        for (int i = 0; i < num_faces; ++i) {`
`            rasterizeImagecoordsKernelCPU(V.data_ptr<float>(), F.data_ptr<int>(), 0,`
`                (INT64*)z_min.data_ptr<int64_t>(), occlusion_truncation, width, height, num_vertices, num_faces, i);`
`        }`
`    } else {`
`        for (int i = 0; i < num_faces; ++i)`
`            rasterizeImagecoordsKernelCPU(V.data_ptr<float>(), F.data_ptr<int>(), D.data_ptr<float>(),`
`                (INT64*)z_min.data_ptr<int64_t>(), occlusion_truncation, width, height, num_vertices, num_faces, i);`
`    }`

`    auto float_options = torch::TensorOptions().dtype(torch::kFloat32).requires_grad(false);`
`    auto barycentric = torch::zeros({height, width, 3}, float_options);`
`    for (int i = 0; i < width * height; ++i)`
`        barycentricFromImgcoordCPU(V.data_ptr<float>(), F.data_ptr<int>(),`
`            findices.data_ptr<int>(), (INT64*)z_min.data_ptr<int64_t>(), width, height, num_vertices, num_faces, barycentric.data_ptr<float>(), i);`

`    return {findices, barycentric};`
`}`

`std::vector<torch::Tensor> rasterize_image(torch::Tensor V, torch::Tensor F, torch::Tensor D,`
`    int width, int height, float occlusion_truncation, int use_depth_prior)`
`{`
`    int device_id = V.get_device();`
`    if (device_id == -1)`
`        return rasterize_image_cpu(V, F, D, width, height, occlusion_truncation, use_depth_prior);`
`    else`
`        return rasterize_image_gpu(V, F, D, width, height, occlusion_truncation, use_depth_prior);`
`}`

`PYBIND11_MODULE(TORCH_EXTENSION_NAME, m) {`
`    m.def("rasterize_image", &rasterize_image, "Custom image rasterization");`
`    m.def("build_hierarchy", &build_hierarchy, "Custom image rasterization");`
`    m.def("build_hierarchy_with_feat", &build_hierarchy_with_feat, "Custom image rasterization");`
`}`
## End rasterizer.cpp

After this modifications, I was able to fully run the `run_nvidia_gpu.bat` file without any problems.

**Comment by SviatoslavPetrov** [comment]
Windows 11 Home
with RTX
ComfyUI 0.3.38 (29.05.2025)

In official documentation exist instruction how to setup [3dWrapper](https://github.com/kijai/ComfyUI-Hunyuan3DWrapper).

Here it is:

Installation
Dependencies, in your python env:

pip install -r requirements.txt

or with portable:

python_embeded\python.exe -m pip install -r ComfyUI\custom_nodes\ComfyUI-Hunyuan3DWrapper\requirements.txt

For the texturegen part compilation is needed, I have included my compilations as a wheel for the rasterizer, and compiled .pyd for the mesh_processor (already in place), these are compiled for:

Windows 11 python 3.12 cu126 (works with torch build on 124)

You would do pip install wheels\custom_rasterizer-0.1-cp312-cp312-win_amd64.whl

or with portable (in ComfyUI_windows_portable -folder): python_embeded\python.exe -m pip install ComfyUI\custom_nodes\ComfyUI-Hunyuan3DWrapper\wheels\custom_rasterizer-0.1-cp312-cp312-win_amd64.whl

Windows 11 python 3.12 torch 2.6.0 + cu126 Current latest portable was updated to use pytorch 2.6.0, for this you should use new wheel: python_embeded\python.exe -m pip install ComfyUI\custom_nodes\ComfyUI-Hunyuan3DWrapper\wheels\custom_rasterizer-0.1.0+torch260.cuda126-cp312-cp312-win_amd64.whl

This was tested to work on latest ComfyUI portable install

**Comment by MarcoHao** [comment]
# 🛠 Fix `custom_rasterizer_kernel` ImportError / AttributeError in ComfyUI

This guide explains how to solve common issues when importing `custom_rasterizer_kernel` in ComfyUI, including `DLL load failed` and `AttributeError: module has no attribute 'rasterize_image'.`

---

## 1️⃣ Basic Information

### 1.1 Locate ComfyUI Python

To find the Python executable ComfyUI is running:

```python
import sys
print(sys.executable)
```

All subsequent operations should be based on this path, for example:

```bash
...\python_embeded\python.exe -m pip install <package>
```

* If using **embedded Python**, it may lack `Include/` and `libs/`.

  * Either download the corresponding Python version and copy `Include/` and `libs/` to your embedded folder.
  * Or use a full Python environment for compilation.

---

### 1.2 Check CUDA & PyTorch Versions

```python
import torch

print("Torch version:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())
if torch.cuda.is_available():
    print("CUDA version (compiled with):", torch.version.cuda)
    print("CUDA device count:", torch.cuda.device_count())
    print("Current device:", torch.cuda.current_device())
    print("Device name:", torch.cuda.get_device_name(torch.cuda.current_device()))

import custom_rasterizer
print(custom_rasterizer.__file__)
```

* If versions are incompatible, reinstall CUDA or PyTorch.
* Ensure Torch DLLs are in `PATH`:

```python
import torch, os
print(os.path.join(os.path.dirname(torch.__file__), 'lib'))
```

---

### 1.3 Check `.pyd` Dependencies

```python
import os
import pefile

def check_pyd_dependencies(pyd_path):
    if not os.path.exists(pyd_path):
        print(f"[ERROR] File not found: {pyd_path}")
        return

    pe = pefile.PE(pyd_path)
    print(f"🔍 Checking dependencies for: {pyd_path}\n")

    dlls = [entry.dll.decode("utf-8") for entry in pe.DIRECTORY_ENTRY_IMPORT]

    if not dlls:
        print("✅ No external DLL dependencies found.")
        return

    print("📂 Required DLLs:")
    for dll in dlls:
        found = any(
            os.path.exists(os.path.join(path, dll))
            for path in os.environ["PATH"].split(";") if path
        )
        status = "✅ Found" if found else "❌ Missing"
        print(f" - {dll:30s} {status}")
```

---

## 2️⃣ Compile `custom_rasterizer_kernel`

### 2.1 Navigate to Source Folder

```bash
cd ...\comfyui-deploy-win\ComfyUI\custom_nodes\ComfyUI-Hunyuan3DWrapper\hy3dgen\texgen\custom_rasterizer
```

Use **ComfyUI's Python executable** in all steps.

---

### 2.2 Build Wheel

```bash
...\python_embeded\python.exe setup.py bdist_wheel
```

---

### 2.3 Install Wheel

```bash
...\python_embeded\python.exe -m pip install --force-reinstall \
  ...\comfyui-deploy-win\ComfyUI\custom_nodes\ComfyUI-Hunyuan3DWrapper\hy3dgen\texgen\custom_rasterizer\dist\custom_rasterizer-0.1.0+torch280.cuda128-cp312-cp312-win_amd64.whl
```

---

### 2.4 Check Installation Path

* The `.pyd` will be imported from:

```
...\hy3dgen\texgen\custom_rasterizer\custom_rasterizer\custom_rasterizer_kernel.cp312-win_amd64.pyd
```

⚠️ Make sure there is **no conflicting package in other site-packages**.

---

### 2.5 Build Extension 
If you need to rebuild `.pyd` after changes:

```bash
cd ...\hy3dgen\texgen\differentiable_renderer
python setup.py build_ext --inplace
```

---

### ✅ Notes & Tips

1. **Embedded Python vs Full Python**

   * Embedded Python often lacks `Include/` and `libs/`.
   * Either supplement them or use a full Python environment to compile extensions.

2. **Check `.pyd` Attributes**

   ```python
   import custom_rasterizer_kernel
   print(dir(custom_rasterizer_kernel))
   ```

   * Ensure `rasterize_image` and other functions exist.

3. **CUDA / PyTorch Compatibility**

   * Match Torch, CUDA, and Python versions.
   * Ensure all DLLs are in `PATH`.

4. **Clean Environment**

   * Remove conflicting packages from other site-packages.
   * Avoid mixing embedded and full Python versions during installation.

---

By following these steps, `custom_rasterizer_kernel` should import successfully and functions like `rasterize_image` will be available.
